apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: barista
    app.openshift.io/runtime: quarkus
  name: barista
spec:
  lookupPolicy:
    local: false