apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/part-of: coffee-shop
  name: coffee-shop-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  # volumeName: pvc-02a06dfb-294f-451f-aab1-05332eb21674
