apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: coffee-shop-database
spec:
  encryptedData:
    database-name: AgByMokT2H8MOEqATkPDC+ySy5INjg5xFoua/XhqHCl+K9wQLD5ZFyoiIXe+Tw8V0498LdwfdlIjg24w4v3lNLPyM6RBV/Y1KSenpebIkySATx1nPlUa/WhMlZ/CDBduLJs9wbzW/m9xSKaaQH3Sq6WTlXx9AyYe4fjmKxtNGJq2TWBi4lSxmfftsbT0DeydpZ3+cDRiU45w6FbSWNifxeFwTZUox6QismHuW8NVfmk85z/ObDpGQoApbW0TkMZVrbe0bm3Wu6gvdTFNCLLPeBQpRlM9oU8F+CaXWZXZFjk1uwY3SotR5GBF9rwE/65U7YRjW9jdVhNofoiioI7X2wGWbSOaHT6xWhbErrHFc/Qkk9yXoRy0MMluQPHI+x+Jwie/9KbxXZBbrPk314HiwMnyQk23mDZx2nZd2zSVeROQwVjh7wr6sfmSRrJtMF5uJjVA3S1fe2bcwLsaShzPflnPLB2DkJMyZsU3IVEA+9iAMyRXkUkbAjnG/mLsTo05yRXOnrvpwlxD7kweVQQt9dcUqd9ihwQ49aZI2sl3NJmo/1OQDvItG4gNLRNoYg5G1Ssc7MPqdqJ/7PC5gk5SSrlkl92swuIPOA6X0qtEAzp3IBzdk6Iuu+TtnAdT+6yNkAlQHG8sxy/yAD6n/YKpA/Nny4rtpNjr4KrtOT9K6kZlSjo96ujb7sx9TyKU+IFIS5cLbSFDHYH88Ojo
    database-password: AgBF80aU+125QUgDSgPWRUt6bb6XdX1IrVstq7AqtYbEJdPjtEtgEfWQpVJ6X0M/McX5dfIsLH83ftJ/DSdpDFYiS59PmF2VVJqd7/jNhn8eaMwHnx4Jjqkk5y2H6TJYqSbGL15hfQldjZegkHj4ay4H/R/ipNLuqeX7robhz7f38DUF0Lumqc9+kru2SweMinxic4gFFmO2pso1G6a7ET8sxTn6+3Rze8Rio9nJYoeSHhED+x8M6mcUdLFtSP9SEFRGJb6W8+VNtLM4aqxkqtksP7vckQqQuB8hcd+Xz2sab52BrOxvvaPtypsDVo7bRthQPlMnsz9Wpx3IWbDgSMmBenAsmx2OlP1UOw+TBnY9084m//SR1cCdNluP2HBcIhPArKUjgRTtZFdaUbWHxdB2p4VX2+2vYXfYobb1IBkNloX4WdZTWNO3fyiH/xtjMZc5vhmqsc6/f5M07bstiwoN3d6s2HiOf5nqVlHCtqnZf+C6bajY3bTetrpwk+u7Hz6X1F09m8hMjwsZeSAwqdx8Dqg46nfG4CQig7Our8UpU3qX9aHzFP5fp0OS9DXghy7+jPEnHs12qHIJ3ZdhDfVfGmSePFlt82sy2DxZSiORVDiRToWH+pzajuV4zkzg9nVry3injN9J/kVPcxHlYXx9QMujUj6wGIc48EyHeMg8e2rpcurQcmFVgmOTZHmNCL3e6ewazTY=
    database-user: AgCudo0Of+FPjfbUUFruru+munZTI0sQ3C/ivVYIVE4h2tlumsMTHASx+zkW+hhH8wqNclUTialwkkrW0hIKyMeo33oBJYmcPnEvmpgTDv/mA17eMbkcpqk7GXjU4iByfO2GCadRCVysYEOqLOEzdBApahyvrGLlwp1n+uTJXgCwQViejh8BuBYQEnaJfs7g5ajndjzg+VhYpTjgDpmok7UKEjZxBg0vwyOLwX7PISJ9q50xfGdKHARofn5Kq5nK57URUnQBI+3qqLWXxGbY2EtZgDrmp7XrTMEK8GrtvzV5dDkxVp72PHYsNdv1EzJc3ED96rk8f3Fz5p6MKXY642O4Wa9uiyfQz/gO3tuSLYdPB0idyVQofQCaDvnNHKj2QuFexVxk78KeaERqamxBM1pwb3CnZRuoK3huzc4BB9+CpMYr6SdAmFRu4xMbu/K17rIrXY6fqcCzAUDPJ0M+Zq4uMzrQqsIN47dusZX8Fw6yqDSVTpmi/FdgmjpkgW7fy3G8vPAwBRmK1ci63KRVLNZcG3gpmtXUVFVCvwYGOAgILMMX24lpJsjyV2CAjyQ347LLN/mrBB0lITrRKEdGHafkcAv3Nb0OHl/RAnavs/Tm2UlkB538+ZFIyBVnAkSJ/X/koNQr5/8z4RXtJ1El46StyGR/mLFdetoBric0fviIQ8WwOlUgx9WwiE+FjFoeEuVb6NpJ8vo=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: coffee-shop
      name: coffee-shop-database
    type: Opaque

