apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: coffee-shop
  name: coffee-shop-database
spec:
  ports:
  - name: postgresql
    port: 5432
  selector:
    name: coffee-shop-database
